apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gf-airflow-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    git: ssh://git@github.com/moanrose/gitops-nginxhello.git
    path: helm/airflow
    ref: master
  rollback:
    enable: true
    retry: true
